### PR TITLE
Auth rework

### LINKED ISSUE #34: Redo Authentication

### PR DESCRIPTION
**Pull request by mehallhm**

### CODE REVIEW

**Review by hmellow — COMMENTED** [review]
I'll need to fix tag-report.js >:(

**Comment by hmellow** [comment]
Please merge #41 to `auth-rework` before merging this branch to main (once checks pass)

**Comment by hmellow** [comment]
> Please merge #41 to `auth-rework` before merging this branch to main (once checks pass)

Done

**Comment by mehallhm** [comment]
I am merging

**Pull request merged**
